eight_points_guzzle:
    logging: true
    clients:
        api_fireping:
            base_url: '%env(SLAVE_URL)%'
            options:
                headers:
                    Accept: "application/json"
                timeout: 20
        alert:
            options:
                headers:
                    Accept: "application/json"
                timeout: 20
