# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - redis-server

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1

# Update composer
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y librrd-dev
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

before_script:
  - pecl install rrd

# Run script
script:
  - phpunit
  - composer phpstan

# After a build, send email notification with the build results
notifications:
  email: jimmy.cleuren@gmail.com