imports:
    - { resource: config_master.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_prod.yml'

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: ["alert"]
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
        alert:
            type: stream
            path:  "%kernel.logs_dir%/alert.%kernel.environment%.log"
            level: info
            channels: [alert]
        console:
            type: console
        syslog_handler:
            type: syslog
            level: info
            channels: [alert]
doctrine:
    orm:
         # enable metadata caching
         metadata_cache_driver: redis
         # enable query caching
         query_cache_driver: redis