imports:
    - { resource: config.yml }
    - { resource: services_master.yml }

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# Nelmio CORS
nelmio_cors:
    defaults:
        allow_origin:   ["%cors_allow_origin%"]
        allow_methods:  ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
        allow_headers:  ["content-type", "authorization"]
        expose_headers: ["link"]
        max_age:        3600
    paths:
        '^/': ~

api_platform:
    collection:
        pagination:
            enabled: false

snc_redis:
    # configure predis as client
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost
            logging: false
        doctrine:
            type: predis
            alias: doctrine
            dsn: redis://localhost
            logging: false
    # configure doctrine caching
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default
            document_manager: default
        result_cache:
            client: doctrine
            entity_manager: [default]
        query_cache:
            client: doctrine
            entity_manager: default

easy_admin:
    site_name: 'Fireping'
    list:
        max_results: 30
        actions:
            - { name: 'show', icon: 'search', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'remove', label: '' }
    show:
        max_results: 20
    entities:
        Domain:
            class: AppBundle\Entity\Domain
            list:
                fields: ['id', 'name', 'parent']
        Device:
            class: AppBundle\Entity\Device
            list:
                fields: ['id', 'name', 'ip', 'domain']
        Alert:
            class: AppBundle\Entity\Alert
            disabled_actions: ['new']
        AlertRule:
            class: AppBundle\Entity\AlertRule
        AlertDestination:
            class: AppBundle\Entity\AlertDestination
        Probe:
            class: AppBundle\Entity\Probe
        ProbeArchive:
            class: AppBundle\Entity\ProbeArchive
        Slave:
            class: AppBundle\Entity\Slave
            disabled_actions: ['new']
        SlaveGroup:
            class: AppBundle\Entity\SlaveGroup