imports:
    - { resource: config.yml }

monolog:
    channels: ["alert"]
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
            formatter: monolog.formatter.standard
        alert:
            type: stream
            path:  "%kernel.logs_dir%/alert.%kernel.environment%.log"
            level: info
            channels: [alert]
            formatter: monolog.formatter.standard
        console:
            type: console
            formatter: monolog.formatter.standard