imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: ["alert"]
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
        alert:
            type: stream
            path:  "%kernel.logs_dir%/alert.%kernel.environment%.log"
            level: info
            channels: [alert]
        console:
            type: console

guzzle:
    logging: true

    clients:
        api_fireping:
            base_url: "https://smokeping-dev.cegeka.be"

            options:
                headers:
                    Accept: "application/json"
