# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    probe_store:
        class:      AppBundle\DependencyInjection\ProbeStore
        arguments:  ["@service_container"]
    instruction_builder:
        class:      AppBundle\DependencyInjection\InstructionBuilderService
        arguments:  ["@service_container"]

    processor.ping:
        class: AppBundle\Processor\PingProcessor
        arguments: ["@service_container"]

    processor.traceroute:
        class: AppBundle\Processor\TracerouteProcessor
        arguments: ["@service_container"]

    graph.ping:
        class: AppBundle\Graph\PingGraph
        arguments: ["@service_container"]

    storage.rrd:
        class: AppBundle\Storage\RrdStorage
        arguments: ["@service_container"]

    snc_second_level_cache:
        class: '%snc_redis.doctrine_cache_predis.class%'
        arguments:
            - '@snc_redis.default'