# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Exception,Form,Instruction,OutputFormatter,Probe,Repository,ShellCommand,Tests,Twig}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        tags: ['controller.service_arguments']

    AppBundle\Controller\DeviceApiController:
        arguments: ["%storage%"]
        tags: ['controller.service_arguments']

    AppBundle\AlertDestination\:
        resource: '../../src/AppBundle/AlertDestination'
        public: true

    AppBundle\AlertDestination\Monolog:
        arguments: ["@monolog.logger.alert"]
        public: true

    AppBundle\AlertDestination\Http:
        arguments: ["@eight_points_guzzle.client.alert", "@monolog.logger"]
        public: true

    AppBundle\Processor\PingProcessor:
        arguments: ["@service_container"]

    AppBundle\Processor\TracerouteProcessor:
        arguments: ["@service_container"]

    AppBundle\Storage\RrdStorage:
        arguments:  ['%storage.path%']

    probe_store:
        class:      AppBundle\DependencyInjection\ProbeStore
        arguments:  ["@service_container"]
        public: true

    instruction_builder:
        class:      AppBundle\DependencyInjection\InstructionBuilderService
        arguments:  ["@service_container"]
        public: true