# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Command,Entity,Exception,Form,Instruction,OutputFormatter,Probe,Processor,Repository,ShellCommand,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        tags: ['controller.service_arguments']

    AppBundle\Storage\RrdStorage:
        arguments:  ['%storage.path%']

    probe_store:
        class:      AppBundle\DependencyInjection\ProbeStore
        arguments:  ["@service_container"]
        public: true

    instruction_builder:
        class:      AppBundle\DependencyInjection\InstructionBuilderService
        arguments:  ["@service_container"]
        public: true

    processor.ping:
        class: AppBundle\Processor\PingProcessor
        arguments: ["@service_container"]
        public: true

    processor.traceroute:
        class: AppBundle\Processor\TracerouteProcessor
        arguments: ["@service_container"]
        public: true